[GeneralConfig]
    DelegationLegacyContractAddress = "erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt"
    LKMEXStakingContractAddress     = "erd1qqqqqqqqqqqqqpgq5kuagsp8cda4mk25xz28zjxen5va7gg9d8ssvqlng0"


[AddressPubkeyConverter]
    #Length specifies the length in bytes of an address
    Length = 32
    # Type specifies the type of public keys: hex or bech32
    Type = "bech32"

[Cloner]
    [Cloner.ElasticSearchClient]
        Address = "http://127.0.0.1:9200"
        Username = ""
        Password = ""

[Reindexer]
    [Reindexer.SourceElasticSearchClient]
        Address = "http://127.0.0.1:9200"
        Username = ""
        Password = ""

    [Reindexer.DestinationElasticSearchClient]
        Address = "http://127.0.0.1:9200"
        Username = ""
        Password = ""

[APIConfig]
    URL = "http://127.0.0.1:7950"
    Username = ""
    Password = ""
